# Writes include\WeaselBuildInfo.h with the git commit this build comes from (called by the
# local build scripts before msbuild). The IME tags its choice statistics with it, so results can
# be compared per version. The file is only rewritten when its content changes.
$ErrorActionPreference = 'SilentlyContinue'
$root = $PSScriptRoot
$out = Join-Path $root 'include\WeaselBuildInfo.h'

$hash = (git -C $root rev-parse --short HEAD 2>$null)
if (-not $hash) { $hash = 'unknown' }
$dirty = if (git -C $root status --porcelain -uno 2>$null) { 1 } else { 0 }
$subject = (git -C $root log -1 --format=%s 2>$null)
if (-not $subject) { $subject = '' }
$time = Get-Date -Format 'yyyy-MM-dd HH:mm'

function Quote([string]$s) { '"' + ($s -replace '\\', '\\' -replace '"', '\"') + '"' }

$text = @"
// Generated by gen_buildinfo.ps1; do not edit.
#pragma once
#define WEASEL_BUILD_HASH L$(Quote $hash)
#define WEASEL_BUILD_DIRTY $dirty
#define WEASEL_BUILD_SUBJECT L$(Quote $subject)
#define WEASEL_BUILD_TIME L$(Quote $time)
"@

# The build time alone does not warrant a rebuild: compare without it
$old = if (Test-Path $out) { Get-Content $out -Raw -Encoding UTF8 } else { '' }
$strip = { param($s) ($s -split "`n" | Where-Object { $_ -notmatch 'WEASEL_BUILD_TIME' }) -join "`n" }
if ((& $strip $old).Trim() -ne (& $strip $text).Trim()) {
  [IO.File]::WriteAllText($out, $text, (New-Object Text.UTF8Encoding $true))
}
