//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeaselDeployer.rc
//
#define IDC_MYICON                      2
#define IDD_WEASELDEPLOYER_DIALOG       102
#define IDI_WEASELDEPLOYER              107
#define IDI_SMALL                       108
#define IDR_MAINFRAME                   128
#define IDD_SWITCHER_SETTING            129
#define IDD_STYLE_SETTING               130
#define IDI_DEPLOY                      131
#define IDD_DICT_MANAGEMENT             132
#define IDS_STR_WEASEL                  133
#define IDS_STR_SAD                     134
#define IDS_STR_HAPPY                   135
#define IDS_STR_NOT_REGULAR             136
#define IDS_STR_DEPLOYING_RESTARTREQ    137
#define IDS_STR_DEPLOYING_WAIT          138
#define IDS_STR_SEL_EXPORT_DICT_NAME    139
#define IDS_STR_ERREXPORT_SYNC_UV       140
#define IDS_STR_ERR_EXPORT_UNKNOWN      141
#define IDS_STR_ERR_EXPORT_SNAP_LOST    142
#define IDS_STR_ERR_UNKNOW              143
#define IDS_STR_ERR_UNKNOWN             143
#define IDS_STR_ERR_SUCCESS             144
#define IDS_STR_ERR_EXPORT_FILE_LOST    145
#define IDS_STR_SEL_IMPORT_DICT_NAME    146
#define IDS_STR_ERR_AT_LEAST_ONE_SEL    147
#define IDS_STR_SCHEMA_NAME             148
#define IDS_STR_OPEN                    149
#define IDS_STR_SAVE_AS                 150
#define IDS_STR_ALL_FILES               151
#define IDS_STR_TXT_FILES               152
#define IDS_STR_IMPORTED                153
#define IDS_STR_EXPORTED                154
#define IDS_STR_RECORD_COUNT            155
#define IDS_STR_DICT_SNAPSHOT           156
#define IDS_STR_KCSS_DICT_SNAPSHOT      157
#define IDS_STR_HELP                    158
#define IDC_SCHEMA_LIST                 1000
#define IDC_SCHEMA_DESCRIPTION          1001
#define IDC_GET_SCHEMATA                1002
#define IDC_HOTKEYS                     1003
#define IDC_COLOR_SCHEME                1004
#define IDC_SELECT_FONT                 1005
#define IDC_PREVIEW                     1006
#define IDC_USER_DICT_LIST              1007
#define IDC_BACKUP                      1008
#define IDC_RESTORE                     1009
#define IDC_EXPORT                      1010
#define IDC_IMPORT                      1011

#define IDD_DIALOG_FONT          1999
#define IDC_CBB_FONTPICKER       2000
#define IDC_CKB_RANGEEN          2001
#define IDC_EDIT_RANGESTART      2002
#define IDC_EDIT_RANGEEND        2003
#define IDC_BTN_ADDFONT          2004
#define IDC_CBB_FONTFACE_NAME    2005
#define IDC_EDIT_FONTFACE        2006
#define IDC_CBB_FONTSTYLE        2007
#define IDC_CBB_FONTWEIGHT       2008
#define IDC_EDIT_PREVIEW_TEXT    2009
#define IDC_CBB_FONTPOINT        2010
#define IDC_STATIC_PREVIEW       2011
#define IDC_STATIC1                     -1

// ---- Unified settings window (SettingsDialog) ----
// Controls are grouped into pages by ID range:
// 30xx shared, 31xx schemas, 32xx appearance, 33xx LLM prediction
#define IDD_SETTINGS                    300
#define IDC_NAV                         3001
#define IDC_PAGE_TITLE                  3002
#define IDC_PAGE_DESC                   3003
#define IDC_APPLY                       3004
#define IDC_STATUS                      3005
#define IDC_SEPARATOR                   3006
#define IDC_THEME_LABEL                 3007
#define IDC_THEME                       3008
#define IDC_P1_HINT                     3101
#define IDC_P1_SCHEMA_LIST              3102
#define IDC_P1_SCHEMA_DESC              3103
#define IDC_P1_HOTKEY_LABEL             3104
#define IDC_P1_HOTKEYS                  3105
#define IDC_P1_GET_SCHEMATA             3106
#define IDC_P1_TYPO_LABEL               3107
#define IDC_P1_TYPO                     3108
#define IDC_P1_TYPO_HINT                3109
#define IDC_P2_SCHEME_LABEL             3201
#define IDC_P2_COLOR_SCHEME             3202
#define IDC_P2_PREVIEW                  3203
#define IDC_P2_FONT_LABEL               3204
#define IDC_P2_FONT_SUMMARY             3205
#define IDC_P2_SELECT_FONT              3206
#define IDC_P3_ENABLED                  3301
#define IDC_P3_AFTER_COMMIT             3302
#define IDC_P3_WHILE_TYPING             3303
#define IDC_P3_MODEL_LABEL              3304
#define IDC_P3_PROFILE                  3305
#define IDC_P3_MANAGE                   3306
#define IDC_P3_LOADED                   3307
#define IDC_P3_TEST_LABEL               3308
#define IDC_P3_TEST_HINT                3309
#define IDC_P3_TEST_INPUT               3310
#define IDC_P3_TEST_RUN                 3311
#define IDC_P3_TEST_RESULT              3312
#define IDC_P3_TEST_STATUS              3313
#define IDC_P3_PREFIX_LABEL             3314
#define IDC_P3_PREFIX_HINT              3315
#define IDC_P3_PREFIX                   3316
#define IDC_P4_ENABLED                  3401
#define IDC_P4_MAX_LABEL                3402
#define IDC_P4_MAX                      3403
#define IDC_P4_HALFLIFE_LABEL           3404
#define IDC_P4_HALFLIFE                 3405
#define IDC_P4_KEEP_LOG                 3406
#define IDC_P4_REFINE_LABEL             3407
#define IDC_P4_INTERVAL_LABEL           3408
#define IDC_P4_INTERVAL                 3409
#define IDC_P4_INTERVAL_HINT            3410
#define IDC_P4_API_HINT                 3411
#define IDC_P4_PROFILE_LABEL            3412
#define IDC_P4_PROFILE                  3413
#define IDC_P4_MANAGE                   3414
#define IDC_P4_DATA_LABEL               3415
#define IDC_P4_STATUS                   3416
#define IDC_P4_REFINE                   3417
#define IDC_P4_REFINE_ALL               3418
#define IDC_P4_CLEAR                    3419
#define IDC_P4_WORDS                    3420
#define IDC_P4_HINT                     3421
#define IDC_P4_RIME_BOOST               3422
#define IDC_P5_HINT                     3501
#define IDC_P5_LIST                     3502
#define IDC_P5_ADD                      3503
#define IDC_P5_COPY                     3504
#define IDC_P5_DELETE                   3505
#define IDC_P5_NAME_LABEL               3506
#define IDC_P5_NAME                     3507
#define IDC_P5_WHERE_LABEL              3508
#define IDC_P5_LOCAL                    3509
#define IDC_P5_LOCAL_LABEL              3510
#define IDC_P5_REMOTE                   3511
#define IDC_P5_REMOTE_LABEL             3512
#define IDC_P5_MODEL_LABEL              3513
#define IDC_P5_MODEL                    3514
#define IDC_P5_BROWSE                   3515
#define IDC_P5_TYPE_LABEL               3516
#define IDC_P5_TYPE                     3517
#define IDC_P5_LOCAL_HINT               3518
#define IDC_P5_API_URL_LABEL            3519
#define IDC_P5_API_URL                  3520
#define IDC_P5_API_KEY_LABEL            3521
#define IDC_P5_API_KEY                  3522
#define IDC_P5_API_MODEL_LABEL          3523
#define IDC_P5_API_MODEL                3524
#define IDC_P5_REMOTE_HINT              3525
#define IDC_P5_USAGE                    3526
#define IDC_P5_FILES_LABEL              3527
#define IDC_P5_FILES                    3528
#define IDC_P5_FILE_ADD                 3529
#define IDC_P5_FILE_DELETE              3530
#define IDC_P5_FILE_OPEN                3531
#define IDC_P5_URL                      3532
#define IDC_P5_DOWNLOAD                 3533
#define IDC_P5_FILE_STATUS              3534
#define IDC_P5_API_TEST                 3535
#define IDC_P6_WORDS_LABEL              3601
#define IDC_P6_FILTER_LABEL             3602
#define IDC_P6_FILTER                   3603
#define IDC_P6_COUNT                    3604
#define IDC_P6_WORDS                    3605
#define IDC_P6_RULES_LABEL              3606
#define IDC_P6_RULES                    3607
#define IDC_P6_WORD                     3608
#define IDC_P6_ADD                      3609
#define IDC_P6_MERGE                    3610
#define IDC_P6_BLOCK                    3611
#define IDC_P6_UNRULE                   3612
#define IDC_P6_REFRESH                  3613
#define IDC_P6_HINT                     3614
#define IDC_P6_DICT_LABEL               3615
#define IDC_P6_DICTS                    3616
#define IDC_P6_BACKUP                   3617
#define IDC_P6_RESTORE                  3618
#define IDC_P6_EXPORT                   3619
#define IDC_P6_IMPORT                   3620
#define IDC_P6_DICT_HINT                3621

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
